name: Release Ubuntu
env:
    GITHUB_TOKEN: ${{ secrets.TOKEN }}
on:
  push:
    tags:
        - '*' 

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release /p:Version="${{ github.ref_name }}" --property WarningLevel=0 --no-restore -o "v${{ github.ref_name }}"      
    - name: tar ubuntu-${{ github.ref_name }}.tar.gz
      run: tar czvf "ubuntu-v${{ github.ref_name }}.tar.gz" "v${{ github.ref_name }}"
    - name: cleanup
      run: rm -r "v${{ github.ref_name }}"
    - name: Add to ${{ github.ref_name }}
      uses: softprops/action-gh-release@v2.2.1
      with:
        name: ubuntu-v${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        files: ubuntu-v${{ github.ref_name }}.tar.gz
